# Generated by Django 5.0.2 on 2024-03-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lesson_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
