# Generated by Django 5.0.2 on 2024-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_lessons_lesson_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['lesson_num']},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(choices=[(0, 'Студент'), (1, 'Преподаватель')], default=0),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['lesson_num'], name='mainapp_les_lesson__0e915d_idx'),
        ),
    ]
