# Generated by Django 5.0.2 on 2024-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='max_students',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='min_students',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
