# Generated by Django 5.0.2 on 2024-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_courses_max_students_courses_min_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='max_students',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='courses',
            name='min_students',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
