# Generated by Django 5.0.2 on 2024-03-02 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_courses_max_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.IntegerField(default=30)),
                ('min_students', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.courses')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='mainapp.groups'),
        ),
    ]
