# Generated by Django 5.0.2 on 2024-03-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_groups_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
